language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - export PIP_USE_MIRRORS=true
  - pip install --upgrade pytest  # https://github.com/travis-ci/travis-ci/issues/4873
install:
  - pip install -e .
script: py.test
